defaults:
  - train: basic
  - data: ap_based_seq
  - model: mtl_lstm_encoder_att_decoder
  - criterions: att_mtl
  - optim: adam
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
